import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { database,migrate } from "../../src/team/db.mjs";
import { createUser } from "../../src/team/auth.mjs";
import { createProject,addMember } from "../../src/team/projects.mjs";
import { workbenchRoute,automationTick } from "../../src/team/workbench.mjs";
import { agentProjectRoute } from "../../src/team/agent-projects.mjs";
import { expertCatalog } from "../../src/team/project-context.mjs";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { publishRunOutputs } from "../../src/team/run-deliverables.mjs";
test("expert catalog preserves resources and maps real member definitions",async()=>{
  assert.ok(expertCatalog.length>=45);
  for(const group of expertCatalog){await fs.access(new URL(`../../src/team/expert-pack/${group.id}/SKILL.md`,import.meta.url));for(const member of group.members)await fs.access(new URL(`../../src/team/expert-pack/${group.id}/${member.file}`,import.meta.url));}
  assert.equal(expertCatalog.find(g=>g.id==="mvp-dev-skills-dsh").members.length,7);
});
test("workbench permissions, private tasks, conflicts, expert import, asset snapshots and recurring runs",{skip:!process.env.TEAM_TEST_DATABASE_URL},async t=>{
  const admin=database(process.env.TEAM_TEST_DATABASE_URL),schema="wb_"+randomUUID().replaceAll("-","");await admin.query(`CREATE SCHEMA ${schema}`);
  const url=new URL(process.env.TEAM_TEST_DATABASE_URL);url.searchParams.set("options",`-c search_path=${schema}`);const db=database(url.href);await migrate(db);
  t.after(async()=>{await db.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
  const pm=await createUser(db,{name:"pm",password:"fixture-password",assignedRoles:["project_manager"]}),dev=await createUser(db,{name:"dev",password:"fixture-password",assignedRoles:["developer"]}),outsider=await createUser(db,{name:"outside",password:"fixture-password",assignedRoles:["developer"]});
  const project=await createProject(db,pm,{name:"Workbench"});await addMember(db,pm,project.id,{userId:dev.id,role:"developer"});
  const call=(u,action,method="GET",input={})=>workbenchRoute(db,u,project.id,"workbench/"+action,method,input);
  await assert.rejects(()=>call(outsider,"config"),/project_access_revoked/);
  await assert.rejects(()=>call(dev,"config","POST",{instructions:"x",skills:[],version:0}),/permission_denied/);
  await call(pm,"config","POST",{instructions:"Use project contract v1",skills:[],version:0});
  await assert.rejects(()=>call(pm,"config","POST",{instructions:"stale",skills:[],version:0}),/edit_conflict/);
  const group="mvp-dev-skills-dsh";const first=await call(pm,"experts","POST",{groupId:group,memberIds:["pm","frontend","qa"]});const second=await call(pm,"experts","POST",{groupId:group,memberIds:["pm","frontend","qa"]});assert.deepEqual(first.agentIds,second.agentIds);
  const privateItem=await call(dev,"items","POST",{title:"Personal task",visibility:"private"});assert.equal((await call(pm,"items")).length,0);
  await assert.rejects(()=>call(pm,`items/${privateItem.id}`,"POST",{version:1,state:"doing"}),/item_not_found/);
  await assert.rejects(()=>call(dev,`items/${privateItem.id}/run`,"POST",{version:1}),/share_before_run/);
  const shared=await call(pm,"items","POST",{title:"Shared task",description:"Build according to contract",assignee:dev.id});
  await call(dev,`items/${shared.id}`,"POST",{version:1,state:"doing"});
  await assert.rejects(()=>call(pm,`items/${shared.id}`,"POST",{version:1,state:"done"}),/edit_conflict/);
  const folder=await call(pm,"assets","POST",{name:"Specifications",folder:true});
  const asset=await call(pm,"assets","POST",{parentId:folder.id,name:"contract.txt",base64:Buffer.from("contract v1").toString("base64")});
  assert.equal(Buffer.from((await call(dev,"assets/"+asset.id)).base64,"base64").toString(),"contract v1");
  await assert.rejects(()=>call(pm,"assets","POST",{name:"../escape",folder:true}));
  await assert.rejects(()=>call(pm,"assets/"+folder.id,"DELETE"),/folder_not_empty/);
  await assert.rejects(()=>call(dev,"assets/"+asset.id,"DELETE"),/permission_denied/);
  await db.query("INSERT INTO team_settings VALUES('agent-model',$1)",[{name:"fixture",baseUrl:"http://fixture/v1"}]);
  const run=await call(dev,`items/${shared.id}/run`,"POST",{version:2,operationId:randomUUID(),agentIds:first.agentIds,repositoryIds:[]});
  const snapshot=await agentProjectRoute(db,dev,project.id,"agent-runs/"+run.id,"GET",{});assert.equal(snapshot.definition.context.instructions,"Use project contract v1");assert.ok(snapshot.definition.context.skills.includes(group));
  await call(pm,"assets/"+asset.id,"DELETE");assert.equal((await db.query("SELECT content FROM team_run_assets WHERE run_id=$1",[run.id])).rows[0].content.toString(),"contract v1");
  const output=await fs.mkdtemp(path.join(os.tmpdir(),"wb-outputs-"));t.after(()=>fs.rm(output,{recursive:true,force:true}));
  await fs.mkdir(path.join(output,"deliverables"));await fs.writeFile(path.join(output,"deliverables","report.txt"),"verified report");await fs.writeFile(path.join(output,"outside.txt"),"must not publish");await fs.symlink(path.join(output,"outside.txt"),path.join(output,"deliverables","link.txt"));
  const rawRun=(await db.query("SELECT * FROM team_agent_runs WHERE id=$1",[run.id])).rows[0];
  const published=await publishRunOutputs(db,rawRun,{results:[{id:"t1",output:"Complete"}]},output);assert.equal(published.length,2);assert.deepEqual(await publishRunOutputs(db,rawRun,{},output),published);
  assert.ok(!(await call(pm,"assets")).some(a=>a.name.endsWith("link.txt")));
  const autoInput={title:"Daily check",goal:"Check project",intervalMinutes:60,nextAt:new Date(Date.now()-1000).toISOString(),agentIds:first.agentIds,repositoryIds:[],autoApprove:true};
  await assert.rejects(()=>call(dev,"automations","POST",autoInput),/permission_denied/);
  await assert.rejects(()=>call(pm,"automations","POST",{...autoInput,autoApprove:false}),/automation_approval_required/);
  const automation=await call(pm,"automations","POST",autoInput);
  await Promise.all([automationTick(db),automationTick(db)]);const row=(await call(pm,"automations"))[0];assert.ok(row.last_run);assert.equal((await db.query("SELECT count(*) FROM team_agent_runs WHERE title='Daily check'")).rows[0].count,"1");
  assert.equal((await agentProjectRoute(db,pm,project.id,"agent-runs/"+row.last_run,"GET",{})).definition.autoApprove,true);
  await db.query("UPDATE team_automations SET next_at=now() WHERE id=$1",[automation.id]);await automationTick(db);assert.equal((await db.query("SELECT count(*) FROM team_agent_runs WHERE title='Daily check'")).rows[0].count,"1");
  await db.query("UPDATE team_users SET active=false WHERE id=$1",[pm.id]);await db.query("UPDATE team_automations SET next_at=now() WHERE id=$1",[automation.id]);await automationTick(db);assert.equal((await db.query("SELECT enabled FROM team_automations WHERE id=$1",[automation.id])).rows[0].enabled,false);
});
