import { chromium } from "playwright";
import { build } from "esbuild";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import assert from "node:assert/strict";
import { database, migrate } from "../src/team/db.mjs";
import { createUser } from "../src/team/auth.mjs";
import { startTeamServer } from "../src/team/server.mjs";
import { createHost } from "../test/team/host-fixture.mjs";

if(!process.env.TEAM_TEST_DATABASE_URL)throw new Error("TEAM_TEST_DATABASE_URL is required");
const schema="ui_"+randomUUID().replaceAll("-","");
const admin=database(process.env.TEAM_TEST_DATABASE_URL);await admin.query(`CREATE SCHEMA ${schema}`);
const url=new URL(process.env.TEAM_TEST_DATABASE_URL);url.searchParams.set("options",`-c search_path=${schema}`);
const db=database(url.href), dir=await fs.mkdtemp(path.join(os.tmpdir(),"team-ui-"));
let app,host,browser;
try{
  await migrate(db);
  await createUser(db,{name:"manager",password:"initial-password-2026",assignedRoles:["project_manager"],admin:true});
  await createUser(db,{name:"developer",password:"initial-password-2026",assignedRoles:["developer"]});
  app=await startTeamServer({db,port:0,model:{baseUrl:"http://test-model.invalid",name:"ui-fixture",timeoutMs:1000},workerOptions:{intervalMs:3600000,generate:async entries=>({summary:"订单接口已讨论使用幂等键避免重复提交。",memories:[{title:"订单接口幂等约定",content:"创建订单请求携带 Idempotency-Key。相同幂等键只创建一次订单；来源为当前项目讨论，尚未附带测试证据。",category:"api-contract",evidence:"reported",sourceIds:[entries[0].id]}]})}});
  const hub=`http://127.0.0.1:${app.server.address().port}`;
  const fixture=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';const root=createRoot(document.getElementById('root'));window.__ModuleLoader__={load(m){const c=[];m.factory(()=>React).apply({slots:{inject(n,f){f()},register(s,C){c.push(React.createElement(C,{key:s.name}))}}});root.render(React.createElement(React.Fragment,null,...c));}};const s=document.createElement('script');s.src='/client.js';document.body.append(s);`,resolveDir:process.cwd()},bundle:true,write:false,format:"iife",platform:"browser"});
  host=await createHost(dir,{
    "/":(_req,res)=>{res.setHeader("content-type","text/html; charset=utf-8");res.end('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="font:14px system-ui;background:#f8f9fb;margin:24px"><div id="root"></div><main style="max-width:560px;margin:80px 0"><h2>订单接口讨论</h2><p>创建订单时使用幂等键，避免重复提交。</p><label>消息<input aria-label="对话输入" style="display:block;width:80%;padding:12px;margin-top:24px"></label></main><script src="/fixture.js"></script></body></html>');},
    "/fixture.js":(_req,res)=>{res.setHeader("content-type","text/javascript");res.end(fixture.outputFiles[0].contents);}
  });
  const events=[];const session={id:"local-orders-session",seq:0,header:{cwd:"/workspace/orders"},snapshotEvents:()=>events};host.sessions.set(session.id,session);
  browser=await chromium.launch({channel:process.env.TEAM_BROWSER_CHANNEL||"chrome",headless:true});
  const page=await browser.newPage({viewport:{width:1365,height:900}}),errors=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto(hub);await page.getByLabel("账号",{exact:true}).fill("manager");await page.getByLabel("密码",{exact:true}).fill("initial-password-2026");await page.getByRole("button",{name:"登录",exact:true}).click();
  await page.getByLabel("当前密码").fill("initial-password-2026");await page.getByLabel("新密码").fill("changed-password-2026");await page.getByRole("button",{name:"保存新密码"}).click();
  await page.getByText("创建项目",{exact:true}).first().click();await page.getByLabel("项目名称").fill("订单平台 · 团队研发");await page.getByRole("button",{name:"创建项目",exact:true}).click();
  await page.getByText("整理模型配置",{exact:true}).click();await page.getByLabel("模型名称",{exact:true}).fill("ui-fixture-updated");await page.getByRole("button",{name:"保存模型配置",exact:true}).click();
  await page.getByRole("button",{name:"项目成员",exact:true}).click();await page.getByLabel("添加项目成员").selectOption({label:"developer"});await page.getByRole("button",{name:"添加成员",exact:true}).click();
  assert.equal(await page.getByText("接受项目邀请",{exact:true}).count(),0);
  await page.getByText("Agent 执行模型",{exact:true}).click();
  await page.getByLabel("执行模型服务地址",{exact:true}).fill("http://fixture-model/v1");
  await page.getByLabel("执行模型名称",{exact:true}).fill("fixture-agent");
  await page.getByRole("button",{name:"保存执行模型",exact:true}).click();
  await page.getByRole("button",{name:"GitLab 仓库",exact:true}).click();
  for(const name of ["frontend","backend"]){
    await page.getByText("关联仓库",{exact:true}).click();
    await page.getByLabel("目录名称（英文、数字、短横线）").fill(name);
    await page.getByLabel("GitLab HTTPS / HTTP 克隆地址").fill(`http://gitlab.yemast.com/test/${name}.git`);
    await page.getByRole("button",{name:"关联",exact:true}).click();
    await page.getByRole("heading",{name,exact:true}).waitFor();
  }
  await page.getByRole("button",{name:"Agent 协作",exact:true}).click();
  for(const name of ["engineer","reviewer"]){
    await page.getByRole("button",{name:"添加 Agent",exact:true}).click();const dialog=page.getByRole("dialog");
    await dialog.getByLabel("名称（英文、数字、短横线）").fill(name);await dialog.getByLabel("职责",{exact:true}).fill(name==="engineer"?"实现跨仓库接口变更":"审查接口与测试");
    await dialog.getByRole("button",{name:"添加",exact:true}).click();await dialog.waitFor({state:"detached"});
  }
  await page.getByRole("button",{name:"发起协作",exact:true}).click();
  await page.getByRole("dialog").getByLabel("任务标题").fill("订单接口联调");await page.getByRole("dialog").getByLabel("目标",{exact:true}).fill("协调前后端接口变更与审查");
  await page.getByRole("button",{name:"生成协作计划",exact:true}).click();
  await page.getByRole("dialog").waitFor({state:"detached"});
  const {rows:[cloudRun]}=await db.query("SELECT * FROM team_agent_runs LIMIT 1");
  assert.equal(cloudRun.definition.repositories.length,2);assert.equal(cloudRun.definition.agents.length,2);
  const activity={captainSessionId:"cloud-captain",members:[{id:"cloud-engineer",name:"engineer",role:"developer",activity:"working",currentTask:"t1",done:0,total:1},{id:"cloud-reviewer",name:"reviewer",role:"qa_engineer",activity:"idle",currentTask:"",done:0,total:1}],tasks:[{id:"t1",subject:"实现订单幂等接口",description:"前后端保持契约一致",state:"running",assignee:"engineer",dependencies:[],depth:0},{id:"t2",subject:"接口验收与审查",description:"验证重复请求的结果",state:"blocked",assignee:"reviewer",dependencies:["t1"],depth:1}]};
  await db.query("UPDATE team_agent_runs SET state='awaiting_approval',summary=$1 WHERE id=$2",[{activity},cloudRun.id]);
  const approval=page.waitForResponse(r=>r.url().endsWith(`/agent-runs/${cloudRun.id}/approve`)&&r.request().method()==="POST");
  await page.getByRole("button",{name:"批准并执行",exact:true}).click();await approval;
  assert.equal((await db.query("SELECT command FROM team_agent_runs WHERE id=$1",[cloudRun.id])).rows[0].command,"approve");
  await db.query("UPDATE team_agent_runs SET state='running' WHERE id=$1",[cloudRun.id]);
  await page.getByText("正在执行 t1",{exact:true}).waitFor();
  assert.equal(await page.locator(".agent-avatar").first().evaluate(img=>img.complete&&img.naturalWidth>0),true);
  await fs.mkdir("artifacts/team-ui",{recursive:true});await page.screenshot({path:"artifacts/team-ui/agent-hub.png",fullPage:true});
  const desktop=await browser.newPage({viewport:{width:1365,height:900}});desktop.on("pageerror",e=>errors.push(e.message));await desktop.goto(host.base);
  await desktop.getByRole("button",{name:"展开团队面板",exact:true}).click();const panel=desktop.frameLocator('iframe[title="团队项目"]');
  const floating=desktop.getByRole("complementary",{name:"团队项目面板"});
  const bounds=await floating.boundingBox();assert.equal(bounds.width,440);assert.ok(bounds.x>850);
  await desktop.getByLabel("对话输入").fill("继续讨论订单接口");
  await panel.getByLabel("内网服务地址").fill(hub);await panel.getByLabel("账号",{exact:true}).fill("developer");await panel.getByLabel("密码",{exact:true}).fill("initial-password-2026");await panel.getByRole("button",{name:"登录",exact:true}).click();
  await panel.getByLabel("当前密码").fill("initial-password-2026");await panel.getByLabel("新密码").fill("changed-password-2026");await panel.getByRole("button",{name:"保存新密码"}).click();
  await panel.getByRole("heading",{name:"关联项目工作区"}).waitFor();await panel.getByRole("button",{name:"关联工作区并同步"}).click();
  await panel.getByRole("button",{name:"插件更新",exact:true}).click();
  await panel.getByText("当前 Desktop 未提供自动安装接口",{exact:true}).waitFor();
  assert.equal(await panel.getByRole("button",{name:"检查并更新",exact:true}).isDisabled(),true);
  await panel.getByLabel("自动更新插件",{exact:true}).uncheck();
  await panel.getByText("运行版本：0.1.0-alpha.15",{exact:true}).waitFor();
  await desktop.screenshot({path:"artifacts/team-ui/plugin-update.png"});
  await panel.getByRole("button",{name:"关闭",exact:true}).click();
  await panel.getByRole("button",{name:"本地绑定",exact:true}).click();
  await panel.locator("tbody").getByText(session.id,{exact:true}).waitFor();
  await panel.getByRole("button",{name:"项目记忆",exact:true}).click();
  await panel.getByText("暂无项目记忆",{exact:true}).waitFor();
  events.push({seq:0,type:"user/message",data:{source:{kind:"user"},content:[{type:"text",text:"订单创建要使用幂等键，避免重复提交。"}]}},{seq:1,type:"turn/end",data:{}});session.seq=2;
  host.ctx.emit("session/event",session,events[1]);
  // A background upload may already be in flight when the sync route returns.
  let memoryReady=false;
  for(let attempt=0;attempt<50;attempt++) {
    await host.call("sync");await app.worker.tick();
    memoryReady=(await db.query("SELECT 1 FROM team_memories LIMIT 1")).rowCount>0;
    if(memoryReady)break;
    await new Promise(resolve=>setTimeout(resolve,100));
  }
  assert.ok(memoryReady,"uploaded messages must finish model processing");
  await host.call("sync");
  await panel.getByRole("heading",{name:"订单接口幂等约定"}).waitFor();
  const managerAuth=await (await fetch(hub+"/team/v1/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:"manager",password:"changed-password-2026",device:"manager-shared"})})).json();
  const projectId=await page.getByLabel("当前项目").inputValue();
  const upload=await fetch(`${hub}/team/v1/projects/${projectId}/source-batches`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${managerAuth.accessToken}`},body:JSON.stringify({profile:"manager-profile",session:"manager-source",operationId:randomUUID(),entries:[{id:"0",role:"user",text:"经理共享的订单验收标准"}]})});assert.equal(upload.status,202);
  await panel.getByRole("button",{name:"会话摘要",exact:true}).click();await panel.locator("article").filter({has:panel.getByRole("heading",{name:"经理共享的订单验收标准"})}).getByRole("button",{name:"查看对话",exact:true}).click();
  await panel.locator(".transcript").getByText("经理共享的订单验收标准",{exact:true}).waitFor();
  await panel.locator("#content").evaluate(section=>{
    window.stableHeading=section.firstElementChild;window.contentMutations=0;window.emptyFrames=0;
    window.contentObserver=new MutationObserver(()=>{window.contentMutations++;if(!section.childElementCount)window.emptyFrames++;});
    window.contentObserver.observe(section,{subtree:true,childList:true,characterData:true});
  });
  await desktop.waitForTimeout(4500);
  assert.deepEqual(await panel.locator("#content").evaluate(s=>({same:window.stableHeading===s.firstElementChild,mutations:window.contentMutations,empty:window.emptyFrames})),{same:true,mutations:0,empty:0});
  const more=await fetch(`${hub}/team/v1/projects/${projectId}/source-batches`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${managerAuth.accessToken}`},body:JSON.stringify({profile:"manager-profile",session:"manager-source",operationId:randomUUID(),entries:[{id:"1",role:"assistant",text:"新增验收条目自动同步"}]})});assert.equal(more.status,202);
  await panel.locator(".transcript").getByText("新增验收条目自动同步",{exact:true}).waitFor();
  assert.equal(await panel.locator("#content").evaluate(()=>window.emptyFrames),0);
  await panel.locator("#content").evaluate(()=>window.contentObserver.disconnect());
  await panel.getByRole("button",{name:"复用会话",exact:true}).click();await panel.getByRole("button",{name:"创建复用会话",exact:true}).click();
  await panel.getByRole("status").filter({hasText:"已创建复用会话"}).waitFor();
  const reused=[...host.sessions.values()].find(s=>s.snapshotEvents().some(e=>e.data?.source?.form==="recall"));
  assert.ok(reused);
  assert.ok(host.workspaces.find(w=>w.id==="orders").sessionIds.includes(reused.id));
  const savedReuse=host.persisted.get(reused.id);
  assert.equal(savedReuse.events[0].type,"turn/start");
  assert.equal(savedReuse.events[2].type,"turn/end");
  assert.equal(savedReuse.events.at(-1).data.title,"复用 · 经理共享的订单验收标准");
  await panel.getByRole("button",{name:"项目记忆",exact:true}).click();
  assert.equal(host.variables.has("team_hub_memory"),false);
  assert.equal(host.contexts.size,0);
  const tool=host.tools.get("team_memory_search");const result=await tool.execute({query:"订单"},{agent:{id:session.id},signal:new AbortController().signal});assert.match(result.text,/幂等/);
  assert.equal((await tool.execute({query:"订单"},{agent:{id:"other-session"},signal:new AbortController().signal})).text,"[]");
  await fs.mkdir("artifacts/team-ui",{recursive:true});
  await desktop.screenshot({path:"artifacts/team-ui/plugin-desktop.png",fullPage:true});
  assert.equal(await panel.locator("nav button.active").evaluate(e=>getComputedStyle(e).color), "rgb(65, 118, 230)");
  await desktop.evaluate(()=>{
    document.body.setAttribute("data-ds-dark-theme", "");
    document.body.style.setProperty("--dsw-alias-bg-layer-1", "#232324");
    document.body.style.setProperty("--dsw-alias-label-primary", "#f9fafb");
  });
  await panel.locator("html[data-ds-dark-theme]").waitFor();
  assert.equal(await panel.locator("html").evaluate(e=>getComputedStyle(e).backgroundColor), "rgba(0, 0, 0, 0)");
  assert.equal(await floating.evaluate(e=>getComputedStyle(e).backgroundColor), "rgba(18, 21, 28, 0.32)");
  await desktop.screenshot({path:"artifacts/team-ui/plugin-dark.png",fullPage:true});
  await desktop.evaluate(()=>{document.body.removeAttribute("data-ds-dark-theme");document.body.style.removeProperty("--dsw-alias-bg-layer-1");document.body.style.removeProperty("--dsw-alias-label-primary");});
  await panel.locator("html:not([data-ds-dark-theme])").waitFor();
  assert.equal(await panel.locator("html").evaluate(e=>getComputedStyle(e).backgroundColor), "rgba(0, 0, 0, 0)");
  assert.deepEqual(await floating.boundingBox(),bounds);
  assert.match(await floating.evaluate(e=>getComputedStyle(e).backdropFilter),/blur\(32px\)/);
  await desktop.getByRole("button",{name:"折叠团队项目",exact:true}).click();assert.equal((await floating.boundingBox()).height,56);
  await desktop.getByRole("button",{name:"展开团队项目",exact:true}).click();
  await panel.getByRole("heading",{name:"订单接口幂等约定"}).waitFor();
  await desktop.getByRole("button",{name:"加宽面板",exact:true}).click();assert.equal((await floating.boundingBox()).width,640);
  await desktop.getByRole("button",{name:"恢复紧凑宽度",exact:true}).click();
  await desktop.getByRole("button",{name:"关闭团队项目",exact:true}).click();assert.equal(await floating.isVisible(),false);
  await desktop.getByRole("button",{name:"团队项目",exact:true}).click();
  await panel.getByRole("heading",{name:"订单接口幂等约定"}).waitFor();
  await desktop.setViewportSize({width:390,height:844});await desktop.screenshot({path:"artifacts/team-ui/plugin-mobile.png",fullPage:true});
  await panel.getByRole("button",{name:"Agent 协作",exact:true}).click();await panel.getByText("正在执行 t1",{exact:true}).waitFor();
  await desktop.screenshot({path:"artifacts/team-ui/agent-plugin-mobile.png",fullPage:true});
  const overflow=await panel.locator("body").evaluate(b=>b.scrollWidth>innerWidth+1);assert.equal(overflow,false);
  await host.call("logout");await host.call("login",{hub,name:"manager",password:"changed-password-2026"});
  await desktop.reload();await desktop.getByRole("button",{name:"展开团队面板",exact:true}).click();
  await panel.getByLabel("当前项目").waitFor();
  await panel.getByRole("button",{name:"稍后",exact:true}).click();
  const stableFrame=await floating.boundingBox();
  await panel.getByLabel("项目管理",{exact:true}).click();
  await panel.getByText("整理模型配置",{exact:true}).click();
  await panel.getByLabel("模型名称",{exact:true}).waitFor();
  assert.deepEqual(await floating.boundingBox(),stableFrame);
  await desktop.screenshot({path:"artifacts/team-ui/plugin-management.png",fullPage:true});
  await panel.getByLabel("项目管理",{exact:true}).click();
  await panel.getByRole("button",{name:"Agent 协作",exact:true}).click();
  await panel.getByRole("button",{name:"添加 Agent",exact:true}).click();
  await panel.getByRole("dialog").waitFor();assert.deepEqual(await floating.boundingBox(),stableFrame);
  await panel.getByRole("button",{name:"取消",exact:true}).click();
  assert.deepEqual(await floating.boundingBox(),stableFrame);
  await page.getByRole("button",{name:"项目工作台",exact:true}).click();
  await page.getByRole("tab",{name:"配置",exact:true}).click();
  await page.getByLabel("项目背景与协作规范").fill("所有交付必须包含验收标准。");
  await page.getByRole("button",{name:"保存项目指令",exact:true}).click();
  await page.getByLabel("搜索专家团").fill("mvp-dev-skills-dsh");
  await page.getByRole("button",{name:"添加专家团",exact:true}).click();
  await page.getByRole("button",{name:"加入项目",exact:true}).click();await page.getByRole("dialog").waitFor({state:"detached"});
  await page.getByText("技能已启用",{exact:true}).waitFor();
  await page.getByRole("tab",{name:"计划",exact:true}).click();
  await page.getByRole("button",{name:"新建待办",exact:true}).click();
  await page.getByLabel("待办标题",{exact:true}).fill("专家团接口验收");await page.getByLabel("任务说明",{exact:true}).fill("验证前后端协议，并输出测试报告。");
  await page.getByLabel("负责人",{exact:true}).selectOption({label:"developer"});
  await page.getByRole("button",{name:"保存待办",exact:true}).click();await page.getByRole("dialog").waitFor({state:"detached"});
  await page.getByRole("heading",{name:"专家团接口验收",exact:true}).waitFor();
  await page.getByLabel("状态：专家团接口验收",{exact:true}).selectOption("doing");
  await page.locator(".plan-doing").getByText("专家团接口验收",{exact:true}).waitFor();
  await page.screenshot({path:"artifacts/team-ui/workbench-plan.png",fullPage:true});
  await page.getByRole("tab",{name:"资产",exact:true}).click();
  await page.getByLabel("上传项目文件",{exact:true}).setInputFiles({name:"验收标准.txt",mimeType:"text/plain",buffer:Buffer.from("HTTP 接口与前端保持一致")});
  await page.getByText("验收标准.txt",{exact:true}).waitFor();
  const downloaded=page.waitForEvent("download");await page.getByRole("button",{name:"下载文件",exact:true}).click();assert.equal((await downloaded).suggestedFilename(),"验收标准.txt");
  await page.getByRole("tab",{name:"配置",exact:true}).click();
  await page.getByRole("button",{name:"新建自动化",exact:true}).click();
  await page.getByLabel("自动化名称",{exact:true}).fill("每日验收检查");await page.getByLabel("执行目标",{exact:true}).fill("检查仓库接口一致性");await page.getByLabel("首次运行",{exact:true}).fill("2099-09-10T09:00");
  await page.getByLabel("允许到期后自动批准并执行任务",{exact:true}).check();await page.getByRole("button",{name:"启用自动化",exact:true}).click();await page.getByRole("dialog").waitFor({state:"detached"});
  await page.getByRole("heading",{name:"每日验收检查",exact:true}).waitFor();await page.getByRole("button",{name:"暂停自动化",exact:true}).click();
  await panel.getByRole("button",{name:"项目工作台",exact:true}).click();await panel.getByRole("tab",{name:"计划",exact:true}).click();await panel.getByRole("heading",{name:"专家团接口验收",exact:true}).waitFor();
  assert.deepEqual(await floating.boundingBox(),stableFrame);assert.equal(await panel.locator("body").evaluate(b=>b.scrollWidth>innerWidth+1),false);
  await desktop.screenshot({path:"artifacts/team-ui/workbench-mobile.png",fullPage:true});
  await page.getByRole("button",{name:"项目记忆",exact:true}).click();await page.getByRole("heading",{name:"订单接口幂等约定"}).waitFor();await page.screenshot({path:"artifacts/team-ui/hub-desktop.png",fullPage:true});
  assert.deepEqual(errors,[]);console.log("Browser workflow passed: model settings, membership, workspace, reuse, multi-repository projects, Agent members, task creation/approval/activity, floating panel, themes and mobile layout.");
}finally{
  await browser?.close();await host?.close();await app?.close();await db.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();await fs.rm(dir,{recursive:true,force:true});
}
